version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      fastmcp:
        patterns:
          - fastmcp
      supabase:
        patterns:
          - supabase
      dev-tools:
        patterns:
          - pytest*
          - pylint

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
